name: Build
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, "ready_for_review"]
  push:
    branches:
      - main

concurrency:
  group: deployment-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Code quality
        uses: ./.github/actions/code-quality
