name: Publish
on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  Publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build app
        uses: ./.github/actions/build
